services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn prueba.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: prueba.settings
      - key: SECRET_KEY
        generateValue: true